[package]
name = "vibettp"
version = "0.1.0"
edition = "2024"

[dependencies.windows-sys]
version = "0.59"
features = [
  "Win32_Networking_WinSock"
]

[dependencies.serde]
version = "1.0.219"
features = [
  "derive"
]

[dependencies]
toml = "0.8.23"
